name: PR Workflow
# Run this workflow every time a new PR is opened to the declared branches
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop

jobs:
  testing:
    name: PR check (Unit tests + Lint)

    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make Gradle commands executable
        run: chmod +x ./gradlew

      - name: Run detekt
        run: ./gradlew detekt
        if: ${{ success() }}

      - name: Run Android Lint
        run: ./gradlew lintDebug
        if: ${{ success() }}

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
        if: ${{ success() }}

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: '**/build/test-results/testDebugUnitTest/*.xml'
